### PR TITLE
fix https://github.com/basiliscos/cpp-bredis/issues/37

### PR DESCRIPTION
**Pull request by Dargun**
https://github.com/basiliscos/cpp-bredis/issues/37

### CODE REVIEW

**Comment by basiliscos** [comment]
Looks ok. I'll look more carefully on the weekends and will merge it. 

Could you, please, meanwhile, add yourself to the contributors (README, changed files headers).

**Comment by Dargun** [comment]
ill updated the changelog and the contributors.

**Comment by Dargun** [comment]
May we should add to this unittests a check with usage of empty values ;)
Ill found that bug with my own project unittests.

**Comment by basiliscos** [comment]
Oh, yes, sure unit tests would be nice  to have :)

**Pull request merged**
