### PR TITLE
Fix deprecated api

### PR DESCRIPTION
**Pull request by miximtor**
Fix deprecated api for boost 1.70.0 compatbility

### CODE REVIEW

**Comment by basiliscos** [comment]
Thank you for your PR. I'll look at it in more details in the weekends. Do you know, why some tests fail?

**Comment by miximtor** [comment]
@basiliscos I pass all test case on linux, Boost version 1.70，I'll try to fix this on boost version 1.69, It seems like that `std::decay_t<WriteCallback>`  and  `std::decay_t<ReadCallback>` cause the fail

**Comment by basiliscos** [comment]
@miximtor I incuded your patch into experimental branch (https://github.com/basiliscos/cpp-bredis/pull/31 )  . The failing tests seems are related to `use_future` bug in previous boost::asio versions ( https://github.com/boostorg/asio/issues/226 ). 

I'll wait a week, and if there will be no reaction, I'll merge my branch and close this one (as I need other features from boost::asio v1.70). Don't you mind, if I'll include you in contributors, then?

**Comment by miximtor** [comment]
That's fine, thanks.

**Comment by basiliscos** [comment]
Merged to master and released `v0.07`.  Closing PR. Thank you, again!

**Pull request closed without merging**
